### ISSUE TITLE
Question about installation 

### ISSUE THREAD

**Issue by eliaswound** [DanuserLab/u-segment3D#2]
Hi this might be a stupid question but for now I tried many other solutions but could not find a better solution for this. I tried this on a windows PC under anaconda enviornment. The first part  `conda create -n u_Segment3D_env python=3.9 cudatoolkit=11.8.* cudnn==8.* -c anaconda` works and when I run `pip install .` it returns 
'Defaulting to user installation because normal site-packages is not writeable
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.'
as the error message. 
Then I tried to install through the yml file `conda env create -f u_Segment3D_env.yml` seems like it can not find package with following error message: 
'Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:'
followed a bunch of package names. 
You mind help with this part in installation?

**Comment by DanuserLab** [comment]
Thanks to Felix for answering the question. The Readme file has been updated accordingly. This ticket is closed now.
